AWSTemplateFormatVersion: "2010-09-09"
Description: Enduro Network Stack (VPC + Public/Private Subnets + IGW + Routes + EC2)

Parameters:
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Existing EC2 KeyPair name (e.g., vockey)

Resources:
  EnduroVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 192.168.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: EnduroVPC

  EnduroIGW:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: EnduroIGW

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref EnduroVPC
      InternetGatewayId: !Ref EnduroIGW

  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref EnduroVPC
      CidrBlock: 192.168.1.0/24
      MapPublicIpOnLaunch: true
      AvailabilityZone: !Select [0, !GetAZs ""]
      Tags:
        - Key: Name
          Value: EnduroPublicSubnet1

  PrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref EnduroVPC
      CidrBlock: 192.168.2.0/24
      MapPublicIpOnLaunch: false
      AvailabilityZone: !Select [0, !GetAZs ""]
      Tags:
        - Key: Name
          Value: EnduroPrivateSubnet1

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref EnduroVPC
      Tags:
        - Key: Name
          Value: EnduroPublicRouteTable

  PublicRoute:
    Type: AWS::EC2::Route
    DependsOn: AttachGateway
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref EnduroIGW

  PublicSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet1
      RouteTableId: !Ref PublicRouteTable

  ManagementSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH (demo) - tighten later
      VpcId: !Ref EnduroVPC
      SecurityGroupIngress:
        # For assignment/demo: allow SSH from anywhere.
        # In real design, restrict to your IP or bastion.
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: EnduroManagementSG

  ManagementEC2:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      KeyName: !Ref KeyName
      SubnetId: !Ref PublicSubnet1
      SecurityGroupIds:
        - !Ref ManagementSG
      ImageId: ami-0c2b8ca1dad447f8a  # Ubuntu 22.04 LTS (us-east-1) - if this fails, we’ll replace with your lab’s allowed AMI
      Tags:
        - Key: Name
          Value: EnduroManagementEC2

Outputs:
  VpcId:
    Description: VPC ID
    Value: !Ref EnduroVPC

  PublicSubnetId:
    Description: Public Subnet ID
    Value: !Ref PublicSubnet1

  InstanceId:
    Description: Management EC2 Instance ID
    Value: !Ref ManagementEC2
