# Resources:
#  Endurovpc :
#    Type: AWS::EC2::VPC
#    Properties:
#      CidrBlock: 192.168.0.0/16
#      EnableDnsSupport: true 
#      Tags:
#        - Key: Name
#          Value: EnduroPublic1
#  EnduroPublicSubnet1:
#      Type: AWS::EC2::Subnet
#       Properties:
#         AvailabilityZone: 
#         Fn::Select: 
#         - 0
#         - Fn::GetAZs: ""
#         VpcId: !Ref Endurovpc
#         MapPublicIpOnLaunch: true
#         CidrBlock: 192.168.1.0/24 
#         Tags:
#           - Key: Name
#             Value: EnduroPublic1 
#  EnduroPrivateSubnet1:
#      Type: AWS::EC2::Subnet
#       Properties:
#         AvailabilityZone: 
#         Fn::Select: 
#         - 0
#         - Fn::GetAZs: ""
#         VpcId: !Ref Endurovpc
#         MapPublicIpOnLaunch: true
#         CidrBlock: 192.168.2.0/24 
#         Tags:
#           - Key: Name
#             Value: EnduroPrivate1 
# Enduroigw:
#   Type: AWS::EC2::InternetGateway
#   Properties:
#     Tags:
#       - Key: Name
#         Value: EnduroIGW
# AttachGateway:  
#   Type: AWS::EC2::VPCGatewayAttachment
#   Properties:
#     VpcId: !Ref Endurovpc
#     InternetGatewayId: !Ref Enduroigw
    
AWSTemplateFormatVersion: "2010-09-09"
Description: >
  Week 2 CloudFormation template to create a VPC with one public subnet, one private subnet, and an Internet Gateway.
  
Resources:

  EnduroVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 192.168.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: EnduroVPC

  EnduroPublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref EnduroVPC
      AvailabilityZone:
        Fn::Select:
          - 0
          - Fn::GetAZs: ""
      CidrBlock: 192.168.1.0/24
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: EnduroPublicSubnet1

  EnduroPrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref EnduroVPC
      AvailabilityZone:
        Fn::Select:
          - 0
          - Fn::GetAZs: ""
      CidrBlock: 192.168.2.0/24
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: EnduroPrivateSubnet1

  EnduroInternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: EnduroIGW

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref EnduroVPC
      InternetGatewayId: !Ref EnduroInternetGateway

Outputs:

  VPCId:
    Description: VPC ID
    Value: !Ref EnduroVPC

  PublicSubnetId:
    Description: Public Subnet ID
    Value: !Ref EnduroPublicSubnet1

  PrivateSubnetId:
    Description: Private Subnet ID
    Value: !Ref EnduroPrivateSubnet1

